name: MATLAB

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch: {}

env:
  MLM_LICENSE_TOKEN: ${{ secrets.MLM_LICENSE_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release: [R2022b, latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v3
        with:
          release: ${{ matrix.release }}
          cache: true

      - name: Run MATLAB build
        uses: matlab-actions/run-build@v3
        with:
          tasks: test

  package:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v3
        with:
          release: latest
          cache: true

      - name: Build toolbox
        uses: matlab-actions/run-build@v3
        with:
          tasks: mltbx

      - name: Upload toolbox artifact
        uses: actions/upload-artifact@v4
        with:
          name: TOML_and_YAML_Toolbox_for_MATLAB.mltbx
          path: release/TOML_and_YAML_Toolbox_for_MATLAB.mltbx
